### PR TITLE
make `.timetrakcer` file more friendly to human.

### PR DESCRIPTION
**Pull request by ipcjs**

### CODE REVIEW

**Review by AlexBlade — COMMENTED** [review]
There is inaccuracy in the description below:
`"description": "Indentation of '.timetracker' file, Set to `4`, which means using 4 spaces as indentation."`
If `number` type will be used as a value type for the parameter then it will work as described but if user will use `string` type ("4" for example) then the string with value "4" will be use as a filler for text indentation. I guess it should be described more accurate. Or maybe it make sense to leave the only type for the parameter's value, `number` for example.

**Comment by ipcjs** [comment]
Some people may want to use tab as an indentation symbol, so I set the parameter type to `string|integer|null`.

maybe we can modify it to:
Indentation of '.timetracker' file. If set to a number, it indicates the number of space characters to use as indentation. If set to a string, the string is used as indentation.

**Comment by AlexBlade** [comment]
It's a good idea. Could you please make changes?

**Comment by ipcjs** [comment]
I have updated the code.

**Comment by AlexBlade** [comment]
The PR was merged. Thanks for your contribution!

**Pull request closed without merging**
